#!/bin/sh
# A pre-commit hook for anything related to validation,
# formatting, and general code quality control.
# Please enhance this file if you believe your addition
# will make everyones life easier.
#
# Author: Gavin Gray
#
# Last modifier: 06.03.2022

# Hook for formatting with clang-format.
# This will grab all modified C/C++ files
# and run clang-format with the provided file
# located in $REPO_ROOT.
for FILE in $(git diff --cached --name-only | grep -E '.*\.(c|cc|cpp|h|hpp)\b')
do
    clang-format -i $FILE
done
